name: manage-azure-policy-46fd8433
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Azure_SQL_MI_should_disable_public_network_access_d42d6380-859d-405f-b82f-152e143b288e/**'
#      - .github/workflows/manage-azure-policy-46fd8433.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_46fd8433}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Azure_SQL_MI_should_disable_public_network_access_d42d6380-859d-405f-b82f-152e143b288e/**
